com:
  sdcsoft:
    datamanage:
      wx-openid: https://apis.sdcsoft.com.cn
spring:
  datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/Iot_Card_Db?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&&useSSL=false&useAffectedRows=true
      username: tomcat
      password: 80201288
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: tomcat
    password: 80201288
    virtual-host: MsgCenter
    template:
      exchange: IotSqlExchange
      routing-key: IotSql
