com:
  sdcsoft:
    datamanage:
      wx-openid: https://apis.sdcsoft.com.cn
spring:
  datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/iot_card_db?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&&useSSL=false&useAffectedRows=true
      username: root
      password: 123456
  rabbitmq:
    host: 192.168.0.110
    port: 5672
    username: tomcat
    password: 80201288
    virtual-host: MsgCenter
    template:
      exchange: IotSqlExchange
      routing-key: IotSql
